# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImgQuit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuitDialog(object):
    def setupUi(self, QuitDialog):
        QuitDialog.setObjectName("QuitDialog")
        QuitDialog.setEnabled(True)
        QuitDialog.resize(359, 141)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuitDialog.sizePolicy().hasHeightForWidth())
        QuitDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(QuitDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.QuitButton = QtWidgets.QPushButton(QuitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuitButton.sizePolicy().hasHeightForWidth())
        self.QuitButton.setSizePolicy(sizePolicy)
        self.QuitButton.setAutoDefault(False)
        self.QuitButton.setObjectName("QuitButton")
        self.horizontalLayout.addWidget(self.QuitButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.CancelButton = QtWidgets.QPushButton(QuitDialog)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)

        self.retranslateUi(QuitDialog)
        QtCore.QMetaObject.connectSlotsByName(QuitDialog)

    def retranslateUi(self, QuitDialog):
        _translate = QtCore.QCoreApplication.translate
        QuitDialog.setWindowTitle(_translate("QuitDialog", "Dialog"))
        self.QuitButton.setText(_translate("QuitDialog", "确定"))
        self.CancelButton.setText(_translate("QuitDialog", "取消"))
