# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(813, 486)
        self.gridLayout = QtWidgets.QGridLayout(MainForm)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(MainForm)
        self.widget.setMinimumSize(QtCore.QSize(640, 360))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoadPicButton = QtWidgets.QPushButton(MainForm)
        self.LoadPicButton.setObjectName("LoadPicButton")
        self.horizontalLayout.addWidget(self.LoadPicButton)
        self.SavePicButton = QtWidgets.QPushButton(MainForm)
        self.SavePicButton.setObjectName("SavePicButton")
        self.horizontalLayout.addWidget(self.SavePicButton)
        self.pushButton = QtWidgets.QPushButton(MainForm)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(MainForm)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.horizontalSlider = QtWidgets.QSlider(MainForm)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(90, 0))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(90, 16777215))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "图片编辑器"))
        self.LoadPicButton.setText(_translate("MainForm", "加载图片"))
        self.SavePicButton.setText(_translate("MainForm", "保存图片"))
        self.pushButton.setText(_translate("MainForm", "测试按钮"))
        self.radioButton.setText(_translate("MainForm", "RadioButton"))
